Repository ThierryRakotomanana/kanban-js, pull requests merged in 2023-06, with the labels that each got.

#3 fixed typo Tast to Task
  index.html
Labels: good first issue

#14 [FIX size]: made box contain task more flexible
  style.css
Labels: bug

#16 [STYLE]: change to dark theme
  style.css
Labels: enhancement
